INSERT INTO backupsbd (id_backupsBD, nombre_backup, ruta_backup, fechaHora) VALUES ('1', 'backup_20240605_222717.sql', 'D:/Medina Jhonatan/Universidad/ProyectosProgramacion/GRNEGOCIO/static/bd/backups/backup_20240605_222717.sql', '2024-06-05 22:27:17');
INSERT INTO moneda (id_moneda, nombreMoneda, codigoMoneda) VALUES ('1', 'D', '$');
INSERT INTO moneda (id_moneda, nombreMoneda, codigoMoneda) VALUES ('2', 'C', 'C$');
INSERT INTO tipo_cliente (id_tipoCliente, nombre_tipoCliente, estado) VALUES ('0', 'Cliente inactivo', '1');
INSERT INTO tipo_cliente (id_tipoCliente, nombre_tipoCliente, estado) VALUES ('2', 'Cliente Normal', '1');
INSERT INTO tipo_cliente (id_tipoCliente, nombre_tipoCliente, estado) VALUES ('3', 'Cliente Especial', '1');
INSERT INTO tipo_cliente (id_tipoCliente, nombre_tipoCliente, estado) VALUES ('4', 'Cliente Fiador', '1');
INSERT INTO tipo_cliente (id_tipoCliente, nombre_tipoCliente, estado) VALUES ('5', 'Cliente en proceso', '1');
INSERT INTO companias_telefonicas (id_compania, nombre_compania, fecha_realizacion, estado) VALUES ('1', 'Claro', '2024-03-14 22:44:41', '1');
INSERT INTO companias_telefonicas (id_compania, nombre_compania, fecha_realizacion, estado) VALUES ('2', 'Tigo', '2024-03-14 22:44:41', '1');
INSERT INTO companias_telefonicas (id_compania, nombre_compania, fecha_realizacion, estado) VALUES ('3', 'Cootel', '2024-03-14 22:44:41', '1');
INSERT INTO companias_telefonicas (id_compania, nombre_compania, fecha_realizacion, estado) VALUES ('4', 'YOTA', '2024-03-14 22:44:41', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('1', 'Jhonatan', 'Medina', '1', '001-150902-1014A', '2024-03-14', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('2', 'Germ', 'Medina Mayorga ', '1', '201-311045-0008S', '2024-03-14', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('3', 'Matilda', 'Louis', '1', '001-211185-003214', '2024-03-18', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('4', 'Lidia Celina', 'Aguirre Santos', '2', '201-311045-0008S', '2024-03-21', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('5', 'Gloria Del Carmen', 'Rodriguez Canales', '2', '201-311045-0008S', '2024-03-22', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('6', 'Ana Gabriel', 'Montoya Canales', '2', '201-311045-0008S', '2024-03-22', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('7', 'Marlen del Rosario', 'Guevara Canales', '2', '201-311045-0008S', '2024-03-23', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('8', 'Germ', 'Medina Mayorga', '1', '201-311045-0008S', '2024-03-25', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('9', 'Denise Nayely ', 'Marchena Aburto ', '1', '', '2024-03-25', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('10', 'Gloria Del Carmen', 'Sobervia', '2', '201-150902-1014D', '2024-03-26', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('11', 'Chihiro ', 'Carmona', '1', '001-150902-1014A', '2024-03-30', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('12', 'Mu', 'Del carmen', '2', '001-150902-1013S', '2024-03-30', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('13', 'Juan', 'Ram', '1', '001-000000-0000A', '1988-02-10', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('14', 'NO HAY', 'NO HAY', '1', '001-000000-000A', '2024-04-27', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('15', 'Marta Gabriela', 'Lucia Cano', '1', '001-189547-002S', '2024-05-03', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('16', 'Juan Carlos', 'Garc', '1', '001-150289-008F', '2024-05-03', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('17', 'Juan Carlos', 'Garc', '1', '001-150289-008F', '2024-05-03', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('18', 'Claudia Jarquin', 'Martinez', '2', '001-281079-0009Y', '1979-10-28', '1');
INSERT INTO persona (id_persona, nombres, apellidos, genero, cedula, fecha_nacimiento, estado) VALUES ('19', 'NO CUENTA CON FIADOR', 'NO CUENTA CON FIADOR', '3', '000-000000-0000A', '2024-06-07', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('1', '1', 'Semaforos de la julio martinez 2c al norte 2c al e', 'Semaforos de la julio martinez 2c al norte 2c al e', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('2', '2', 'El chilamate ', 'Semaforos de la julio martinez 2c al norte 2c al e', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('3', '1', 'dafsaf', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('4', '1', 'Del 5c al Este 3 c al Oeste', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('5', '1', 'No se xd', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('6', '1', 'NO SE 2', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('7', '1', 'DUDOSA PROCEDENCIA', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('8', '1', 'El chilamate', 'El chilamate', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('9', '1', 'En el mero san judas', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('10', '1', 'El mero San Judas tambi', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('11', '1', 'Del chilamate 3 cuadras arriba', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('12', '1', 'No s', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('13', '1', 'Por el mercado oriental', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('14', '1', 'NO HAY', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('15', '1', 'Hasta el sur', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('16', '1', 'Me gusta el pan', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('17', '1', 'Me gusta el pan', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('18', '1', 'Praderas del doral 4ta Etapa, alueda 3c-633', '', '1');
INSERT INTO direccion (id_direccion, nombre_direccion, direccion_escrita, direccion_mapa, estado) VALUES ('19', '1', 'NO CUENTA CON FIADOR', '', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('1', '2', '2', '81719517', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('2', '1', '2', '87393929', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('3', '1', '1', '76785562', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('4', '1', '1', '76785562', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('5', '1', '1', '85920121', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('6', '1', '1', '85920121', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('7', '1', '2', '85513587', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('8', '2', '1', '87393929', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('9', '2', '2', '85920121', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('10', '1', '1', '81719517', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('11', '2', '2', '85920121', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('12', '2', '2', '76789975', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('13', '2', '2', '85636879', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('14', '1', '3', '87979879', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('15', '1', '1', '85920121', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('16', '1', '2', '85920125', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('17', '1', '2', '85920125', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('18', '2', '2', '85130836', '1');
INSERT INTO telefono (id_telefono, id_compania, nombre_telefono, numero_telefono, estado) VALUES ('19', '1', '3', '0', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('1', '1', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('2', '2', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('3', '3', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('4', '4', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('5', '5', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('6', '6', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('7', '7', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('8', '8', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('9', '9', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('10', '10', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('11', '11', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('12', '12', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('13', '13', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('14', '14', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('15', '15', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('16', '16', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('17', '17', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('18', '18', '1');
INSERT INTO persona_direccion (id_persona, id_direccion, estado) VALUES ('19', '19', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('1', '1', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('2', '2', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('3', '3', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('4', '4', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('5', '5', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('6', '6', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('7', '7', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('8', '8', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('9', '9', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('10', '10', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('11', '11', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('12', '12', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('13', '13', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('14', '14', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('15', '15', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('16', '16', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('17', '17', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('18', '18', '1');
INSERT INTO direccion_telefono (id_direccion, id_telefono, estado) VALUES ('19', '19', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('1', '1', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('2', '2', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('3', '3', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('4', '4', '3', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('5', '5', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('6', '6', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('7', '7', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('8', '8', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('9', '9', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('10', '10', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('11', '11', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('12', '12', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('13', '13', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('14', '14', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('15', '15', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('16', '16', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('17', '18', '2', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO cliente (id_cliente, id_persona, id_tipoCliente, imagenCliente, imagenCedula, estado) VALUES ('18', '19', '4', '<FileStorage: \'\' (\'application/octet-stream\')>', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('1', '1', '2', '3', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('2', '3', '2', '5', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('3', '4', '1', '5', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('4', '7', '2', '3', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('5', '9', '2', '2', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('6', '11', '1', '4', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('7', '13', '1', '7', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('8', '16', '1', '3', 'Informatica', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato_fiador (id_contrato_fiador, id_cliente, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, estado) VALUES ('9', '18', '4', '6', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('1', '1', '1', '1', '4', 'Yucalteca', '<FileStorage: \'\' (\'application/octet-stream\')>', '596.00', '1', '18.00', '107.28', '53.64', '2024-03-14', '2024-09-26', '15', '7.16', '2024-03-14 23:10:54', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('2', '3', '2', '2', '2', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '300.00', '1', '18.00', '54.00', '27.00', '2024-03-22', '2024-12-11', '15', '16.20', '2024-03-22 00:14:01', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('3', '4', '3', '1', '5', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '500.00', '1', '18.00', '90.00', '45.00', '2024-03-22', '2025-07-25', '30', '27.00', '2024-03-22 00:16:16', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('4', '7', '4', '1', '1', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '590.00', '1', '18.00', '106.20', '53.10', '2024-03-25', '2024-09-28', '15', '21.24', '2024-03-25 16:11:34', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('5', '9', '5', '2', '4', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '300.00', '1', '18.00', '54.00', '27.00', '2024-03-26', '2024-11-22', '15', '9.00', '2024-03-26 23:26:53', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('6', '11', '6', '1', '3', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '596.00', '1', '18.00', '107.28', '53.64', '2024-03-21', '2024-11-22', '15', '35.80', '2024-03-30 23:57:42', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('7', '13', '7', '2', '7', 'Informatica', '<FileStorage: \'\' (\'application/octet-stream\')>', '1077.00', '1', '15.00', '161.55', '80.78', '2023-02-21', '2023-12-20', '15', '53.90', '2024-04-27 10:02:09', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('8', '15', '8', '2', '1', 'Atenci', '<FileStorage: \'\' (\'application/octet-stream\')>', '300.00', '1', '18.00', '54.00', '27.00', '2024-05-03', '2024-11-23', '15', '23.40', '2024-05-03 21:56:47', '1');
INSERT INTO contrato (id_contrato, id_cliente, id_contrato_fiador, estado_civil, nombre_delegacion, dptoArea_trabajo, ftoColillaINSS, monto_solicitado, tipo_monedaMonto_solicitado, tasa_interes, pagoMensual, pagoQuincenal, fechaPrestamo, fechaPago, intervalo_tiempoPago, montoPrimerPago, fechaCreacionContrato, estado) VALUES ('9', '17', '9', '1', '6', 'Informatica', '<FileStorage: \'\' (\'application/octet-stream\')>', '809.00', '1', '18.00', '145.62', '72.81', '2024-05-14', '2024-12-31', '15', '9.70', '2024-06-07 00:47:37', '1');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('1', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2023-02-17', '2024-04-27 10:45:32', '3');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('2', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-01-31', '2024-04-27 15:58:01', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('3', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-02-04', '2024-04-27 15:58:46', '2');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('4', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-02-04', '2024-04-27 15:59:15', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('5', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-02-20', '2024-04-27 16:00:37', '2');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('6', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-02-20', '2024-04-27 16:01:00', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('7', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-03-07', '2024-04-27 16:05:02', '2');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('8', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-03-07', '2024-04-27 16:05:35', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('9', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-03-25', '2024-04-27 16:09:35', '2');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('10', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-03-25', '2024-04-27 16:09:49', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('11', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-15', '2024-04-27 16:11:05', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('12', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-18', '2024-04-27 16:11:25', '2');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('13', '7', '13', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-18', '2024-04-27 16:11:46', '0');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('14', '4', '7', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-01', '2024-04-27 17:28:37', '3');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('15', '4', '7', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-27', '2024-04-27 17:28:45', '1');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('16', '8', '15', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-05-03', '2024-05-03 21:57:03', '3');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('17', '8', '15', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-06-04', '2024-06-04 17:21:59', '1');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('18', '9', '17', 'Este pago es solamente simb�lico para el sistema, ya que este cuenta es vieja pero hasta ahora se est� ingresando al sistema.', '<FileStorage: \'\' (\'application/octet-stream\')>', '2023-01-01', '2024-06-07 00:48:47', '3');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('19', '9', '17', '', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-05-15', '2024-06-07 00:51:21', '1');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('20', '9', '17', 'Est� pago se realiz� el d�a 06 de Junio de 2024', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-05-30', '2024-06-07 00:53:18', '1');
INSERT INTO pagos (id_pagos, id_contrato, id_cliente, observacion, evidencia_pago, fecha_pago, fecha_realizacion_pago, estado) VALUES ('21', '9', '17', 'T� pagaste $600 d�lares - $400 del capital d�lares 

Te quedan $200 d�lares 

Menos los intereses al 12 de Mayo $109 d�lares por lo tanto los $91 d�lares que sobran te lo resto a t� deuda que era de $900 d�lares 

 Saldo a la fecha:�$809', '<FileStorage: \'\' (\'application/octet-stream\')>', '2024-04-30', '2024-06-07 00:59:06', '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('1', '1', '1', '53.90', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('2', '2', '1', '706.13', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('3', '2', '2', '25773.88', '36.50', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('4', '3', '1', '21.86', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('5', '3', '2', '800.00', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('6', '4', '1', '58.92', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('7', '5', '1', '60.11', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('8', '5', '2', '2200.00', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('9', '6', '1', '20.67', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('10', '7', '1', '35.52', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('11', '7', '2', '1300.00', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('12', '8', '1', '45.26', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('13', '9', '1', '35.52', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('14', '9', '2', '1300.00', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('15', '10', '1', '45.26', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('16', '11', '1', '80.78', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('17', '12', '1', '19.13', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('18', '12', '2', '700.00', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('19', '13', '1', '61.65', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('20', '14', '1', '21.24', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('21', '15', '1', '53.10', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('22', '16', '1', '23.40', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('23', '17', '1', '27.00', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('24', '18', '1', '9.70', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('25', '19', '1', '72.81', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('26', '19', '2', '2664.85', '36.60', '2');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('27', '20', '1', '72.81', NULL, '1');
INSERT INTO detalle_pagos (id_detalle_pagos, id_pagos, id_moneda, cifraPago, tasa_conversion, estado) VALUES ('28', '21', '1', '72.81', NULL, '1');
INSERT INTO saldos_pagos (id_saldos_pagos, id_cliente, id_moneda, cifraSaldo, fecha_saldo, estado) VALUES ('1', '13', '1', '-1018.67', '2024-04-27 16:11:46', '1');
INSERT INTO tasacambiomoneda (id_tasaCambioMoneda, moneda_origen, moneda_destino, cifraTasaCambio, cifraTasaCambioAnterior, fechaModificacion) VALUES ('1', '1', '2', '36.60', '36.80', '2024-03-19 00:10:51');
INSERT INTO tiposaldos_pagos (id_tipoSaldos_pagos, nombreTipoSaldo_pago, simboloSaldos_pagos, estado) VALUES ('1', 'A favor', '+', '1');
INSERT INTO tiposaldos_pagos (id_tipoSaldos_pagos, nombreTipoSaldo_pago, simboloSaldos_pagos, estado) VALUES ('2', 'En contra', '-', '1');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('1', '1', '2', '2', '-706.13', 'Disminucion', '2024-04-27 15:58:01');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('2', '1', '4', '1', '-58.92', 'Disminucion', '2024-04-27 15:59:15');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('3', '1', '6', '1', '-20.67', 'Disminucion', '2024-04-27 16:01:00');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('4', '1', '8', '1', '-45.26', 'Disminucion', '2024-04-27 16:05:35');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('5', '1', '10', '1', '-45.26', 'Disminucion', '2024-04-27 16:09:49');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('6', '1', '11', '1', '-80.78', 'Disminucion', '2024-04-27 16:11:05');
INSERT INTO transacciones_saldos (id_transaccion, id_saldos_pagos, id_pagos, id_moneda, monto, tipo_transaccion, fecha_transaccion) VALUES ('7', '1', '13', '1', '-61.65', 'Disminucion', '2024-04-27 16:11:46');